import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';

import '../../../../core/utils/currency_formatter.dart';
import '../../../../shared/theme/app_colors.dart';
import '../../../../shared/theme/app_spacing.dart';
import '../../../../shared/theme/app_text_styles.dart';
import '../../../../shared/widgets/navigation/app_header.dart';
import '../../../../shared/widgets/navigation/standalone_shell_scaffold.dart';
import 'account_page.dart';

class _Order {
  const _Order({
    required this.id,
    required this.date,
    required this.status,
    required this.paymentMethod,
    required this.total,
  });

  final String id;
  final DateTime date;
  final String status;
  final String paymentMethod;
  final int total;
}

// Placeholder data until order history is wired up to a backend — real
// order IDs will be generated by Firebase, so these use a plain sequential
// form rather than mimicking that generated shape.
final List<_Order> _sampleOrders = [
  _Order(
    id: '#ORD1004',
    date: DateTime(2025, 3, 19),
    status: 'PENDING',
    paymentMethod: 'Cash on Delivery',
    total: 2125,
  ),
  _Order(
    id: '#ORD1003',
    date: DateTime(2025, 3, 15),
    status: 'COMPLETED',
    paymentMethod: 'Cash on Delivery',
    total: 1086,
  ),
  _Order(
    id: '#ORD1002',
    date: DateTime(2024, 9, 21),
    status: 'CANCELLED',
    paymentMethod: 'SSLCommerz',
    total: 1293,
  ),
  _Order(
    id: '#ORD1001',
    date: DateTime(2024, 6, 4),
    status: 'COMPLETED',
    paymentMethod: 'Cash on Delivery',
    total: 866,
  ),
];

/// Full-screen order-history page, reached from [AccountPage]. Pushed on the
/// root navigator the same way [AccountPage] is (see `app_router.dart`), so
/// it gets the same drawer/end-drawer/bottom-nav chrome via
/// [StandaloneShellScaffold].
class OrderHistoryPage extends StatelessWidget {
  const OrderHistoryPage({super.key});

  @override
  Widget build(BuildContext context) {
    return const StandaloneShellScaffold(body: _OrderHistoryView());
  }
}

class _OrderHistoryView extends StatelessWidget {
  const _OrderHistoryView();

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Column(
        children: [
          AppHeader(
            showSearchBar: false,
            onMenuTap: () => Scaffold.of(context).openDrawer(),
            onAccountTap: () => openAccountMenu(context),
          ),
          Expanded(
            child: ListView.separated(
              padding: const EdgeInsets.all(AppSpacing.md),
              itemCount: _sampleOrders.length,
              separatorBuilder: (_, _) => const SizedBox(height: AppSpacing.md),
              itemBuilder: (context, index) => _OrderCard(order: _sampleOrders[index]),
            ),
          ),
        ],
      ),
    );
  }
}

class _OrderCard extends StatelessWidget {
  const _OrderCard({required this.order});

  final _Order order;

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        color: AppColors.surface,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(color: Colors.black.withValues(alpha: 0.14), blurRadius: 6, offset: const Offset(0, 2)),
        ],
      ),
      clipBehavior: Clip.antiAlias,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            width: double.infinity,
            padding: const EdgeInsets.symmetric(horizontal: AppSpacing.md, vertical: AppSpacing.sm),
            color: AppColors.primary,
            child: Text.rich(
              TextSpan(
                children: [
                  TextSpan(text: '${'order_history.order_id'.tr()}  ', style: AppTextStyles.body.copyWith(color: Colors.white)),
                  TextSpan(
                    text: order.id,
                    style: AppTextStyles.body.copyWith(color: Colors.white, fontWeight: FontWeight.bold),
                  ),
                ],
              ),
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(AppSpacing.md),
            child: Column(
              children: [
                _OrderRow(label: 'order_history.order_date'.tr(), value: DateFormat.yMMMMd().format(order.date)),
                const SizedBox(height: AppSpacing.xs),
                _OrderRow(label: 'order_history.order_status'.tr(), value: order.status),
                const SizedBox(height: AppSpacing.xs),
                _OrderRow(label: 'order_history.payment_method'.tr(), value: order.paymentMethod),
                const SizedBox(height: AppSpacing.xs),
                _OrderRow(label: 'order_history.total'.tr(), value: formatYen(order.total)),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _OrderRow extends StatelessWidget {
  const _OrderRow({required this.label, required this.value});

  final String label;
  final String value;

  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(label, style: AppTextStyles.body.copyWith(color: AppColors.textSecondary)),
        Text(value, style: AppTextStyles.body.copyWith(color: AppColors.textPrimary, fontWeight: FontWeight.w600)),
      ],
    );
  }
}
