// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwfNp15RySBOLkPC0CJUCdfg-5PqnZxu4',
    appId: '1:339861351370:web:0cebbf8118e885a1ce3d33',
    messagingSenderId: '339861351370',
    projectId: 'everyday-wholesale',
    authDomain: 'everyday-wholesale.firebaseapp.com',
    storageBucket: 'everyday-wholesale.firebasestorage.app',
    measurementId: 'G-T08QCKFB29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsNFb4qFWIfERv59NTm-TV4muKBL6b0JE',
    appId: '1:339861351370:android:6512b973e8555461ce3d33',
    messagingSenderId: '339861351370',
    projectId: 'everyday-wholesale',
    storageBucket: 'everyday-wholesale.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfyOM9XfZit3cPUxpUWdNH8RNXxZWguGA',
    appId: '1:339861351370:ios:57e54cd93b7e1517ce3d33',
    messagingSenderId: '339861351370',
    projectId: 'everyday-wholesale',
    storageBucket: 'everyday-wholesale.firebasestorage.app',
    iosBundleId: 'com.example.everydayWholesale',
  );
}
